ninetyninecats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

ninetyninecats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninetyninecats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  COLORS = ['black', 'white', 'yellow', 'grey']
  
  validates :sex, inclusion: { in: %w(m f M F) }
  validates :color, inclusion: { in: COLORS }

  def age
    Time.now.year - birth_date.year
  end
end

ninetyninecats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninetyninecats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end
  
  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new 
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      # show user the cat show page
      redirect_to cat_url(@cat)
    else
      # show user the new cat form
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end


  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end

end

ninetyninecats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninetyninecats/app/helpers/cats_helper.rb
module CatsHelper
end

ninetyninecats/app/views/cats/edit.html.erb
<% cat = @cat %>

<form action="<%= cat_url(cat) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">

  <br>

  <label for="birth_date">Birth_date</label>
  <input id="birth_date" type="text" name="cat[birth_date]" value="<%= cat.birth_date %>">

  <br>

  <label for="color">Color</label>
  <input id="color" type="text" name="cat[color]" value="<%= cat.color %>">

  <br>

  <label for="sex">Sex</label>
  <input id="sex" type="text" name="cat[sex]" value="<%= cat.sex %>">

  <br><br>

  <label for="description">Description</label>
  <textarea name="cat[description]">
    <%= cat.description %>
  </textarea>

  <input type="submit" value="Edit a cat!">
</form>

ninetyninecats/app/views/cats/index.html.erb
<h1>All the cats!</h1>

<ul>

  <% @cats.each do |cat| %>
      
    <li><%= cat.name %></li> 
      
  <% end %>
  <!-- <li><%#= render @cats %></li> -->
</ul>

ninetyninecats/app/views/cats/new.html.erb
<% cat = @cat %>

<form action="<%= cats_url %>" method="post">
 
  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="">

  <br>

  <label for="birth_date">Birth_date</label>
  <input id="birth_date" type="text" name="cat[birth_date]" value="">

  <br>

  <label for="color">Color</label>
  <input id="color" type="text" name="cat[color]" value="">

  <br>

  <label for="sex">Sex</label>
  <input id="sex" type="text" name="cat[sex]" value="">

  <br><br>

  <label for="description">Description</label>
  <textarea name="cat[description]">

  </textarea>

  <input type="submit" value="Add a cat!">
</form>

ninetyninecats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table border="1">
  <tr>
    <th>Age:</th> 
    <th>Color:</th> 
    <th>Sex:</th> 
  </tr>
  <tr>
    <td align=center><%= @cat.age%></td>
    <td align=center><%= @cat.color%></td>
    <td align=center><%= @cat.sex%></td>
  </tr>
</table>

<p>
  <%= @cat.description %>
</p>
<!-- 

# birth_date :date not null
# color :string not null
# name :string not null
# sex :string(1) not null
# description :text not null -->

ninetyninecats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ninetyninecats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>